version: '3.8'

services:
  ghost:
    image: ghost:5
    environment:
      url: http://localhost:4000
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost_data:/var/lib/ghost/content

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GHOST_URL=http://ghost:2368
      - PORT=4000
      - DEBUG=true
      - BUNNYCDN_API_KEY=<your-bunnycdn-api-key>
      - BUNNYCDN_PULL_ZONE_ID=<your-bunnycdn-pull-zone-id>
      - BUNNYCDN_PURGE_OLD_CACHE=true
      - BUNNYCDN_STORAGE_ZONE_NAME=<your-bunnycdn-storage-zone-name>
      - BUNNYCDN_STORAGE_ZONE_PASSWORD=<your-bunnycdn-storage-zone-password>
    ports:
      - "4000:4000"
    depends_on:
      - ghost

volumes:
  ghost_data:
